#!/bin/bash
version="${@:-master}"
workdir=$(pwd)
docker run -ti --rm -e DOCKERTAG=$version -w ${workdir} -v /var/run/postgresql:/var/run/postgresql -v /home/$USER/:/home/$USER/:ro -v /home/$USER/.local/share/Odoo:/home/$USER/.local/share/Odoo ${@:2} -p 127.0.0.1:8069:8069/tcp -p 127.0.0.1:8070:8070/tcp  runbot_image:$version /bin/bash
